/*
 * config.h
 *
 *  Created on: Nov 15, 2025
 *      Author: ASUS
 */

#ifndef INC_CONFIG_H_
#define INC_CONFIG_H_

// CONFIG FLAG FOR TFT LCD
#define TFT_ENABLE_SPI_TEST 0
#define TFT_ENABLE_TIMING 1
#define TFT_ENABLE_SERIAL_LOG 1

#define TFT_ENABLE_CONVERT_DMS 0

// CONFIG FLAG FOR IMU
#define IMU_ENABLE_SERIAL_LOG 0
#define IMU_UKF_ENABLE_SERIAL_LOG 0

// CONFIG FLAG FOR BATTERY
#define BATTERY_ENABLE_SERIAL_LOG 1

// CONFIG FLAG FOR GPS
#define GPS_ENABLE_SERIAL_LOG 1

// CONFIG FLAG FOR LORA
#define LORA_ENABLE_SERIAL_LOG 0
#define LORA_TEST_TRANSFER 1


#endif /* INC_CONFIG_H_ */
